languageCode = "en"
languageName = "English"
weight = 1
title = "Screamer Alliance WFC"
contentDir = "content/en"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "We are Screamer Alliance Women's Football Club founded in March 2024"
dateFormat = "2 January 2006"
author = { name = "Screamer Alliance WFC", image = "img/avatar.png", headline = "We write our Screamer 'herstory' here", bio = "A little bit about you", links = [ { link = "https://screameralliancewfc.github.io/" }, { instagram = "https://www.instagram.com/screameralliancewfc/" } ] }
